name: Python Flask CI Build

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "feature/*" ]

jobs:
  build-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Build
        run: docker build . --file Dockerfile --tag pythonflaskapiv2:latest
